version: "3.9"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      PRICE_SVC_URL: http://svc-pricing-go:8080
      ML_SVC_URL: http://svc-ml-py:8000
    depends_on:
      - svc-pricing-go
      - svc-ml-py

  svc-pricing-go:
    build:
      context: ./svc-pricing-go
      # use Dockerfile.debug only if you’re running Delve, else omit this line
      # dockerfile: Dockerfile.debug
    environment:
      MONGODB_URI: "mongodb+srv://<db_username>:<db_password>@cluster0.qruelfp.mongodb.net/"
      ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}
    ports:
      - "8080:8080"     # service port
      - "40000:40000"   # Delve (only if using Dockerfile.debug)
    # if you’re NOT debugging, you can drop the 40000 line
    restart: unless-stopped

  svc-ml-py:
    build: ./svc-ml-py
    expose:
      - "8000"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE: http://localhost:3001
    depends_on:
      - api-gateway

networks:
  default:
    name: stock-net
