version: "3.9"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      PRICE_SVC_URL: http://svc-pricing-go:8080
      ML_SVC_URL: http://svc-ml-py:8000
    depends_on:
      - svc-pricing-go
      - svc-ml-py

  svc-pricing-go:
    build: ./svc-pricing-go
    expose:
      - "8080"
    environment:
      ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}

  svc-ml-py:
    build: ./svc-ml-py
    expose:
      - "8000"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE: http://localhost:3001
    depends_on:
      - api-gateway

networks:
  default:
    name: stock-net
